
import java.security.InvalidKeyException;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author khavy
 */
public class RSA extends javax.swing.JFrame {

    private static RSA checkRSA = null;
    
    public RSA() {
        initComponents();
        setDefaultCloseOperation(RSA.DISPOSE_ON_CLOSE);

    }
    public static RSA testGuiRSA(){
        if(checkRSA == null){
            checkRSA = new RSA();
        }
        return checkRSA;
    }
    
    private void randomKey() throws NoSuchAlgorithmException, InvalidKeySpecException 
    {
        SecureRandom sr = new SecureRandom();
        KeyPairGenerator kpg = KeyPairGenerator.getInstance("RSA");
        kpg.initialize(1024, sr);
        KeyPair kp = kpg.genKeyPair();
        PublicKey publicKey = kp.getPublic();
        PrivateKey privateKey = kp.getPrivate();
        txtkeypublic.setText(Base64.getEncoder().encodeToString(publicKey.getEncoded())) ;
        txtprivatekey.setText(Base64.getEncoder().encodeToString(privateKey.getEncoded()));
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtkeypublic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtprivatekey = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtinput = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtcipher = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtplain = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnencryp = new javax.swing.JButton();
        btndecryp = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuFile = new javax.swing.JMenuItem();
        menuFile1 = new javax.swing.JMenuItem();
        menuFile2 = new javax.swing.JMenuItem();
        menuFile3 = new javax.swing.JMenuItem();
        menuFile4 = new javax.swing.JMenuItem();
        menuFile5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("RSA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("KEY PUBLIC:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("KEY PRIVATE:");

        txtprivatekey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprivatekeyActionPerformed(evt);
            }
        });

        txtinput.setColumns(20);
        txtinput.setLineWrap(true);
        txtinput.setRows(5);
        txtinput.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtinput);

        txtcipher.setColumns(20);
        txtcipher.setLineWrap(true);
        txtcipher.setRows(5);
        txtcipher.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtcipher);

        txtplain.setColumns(20);
        txtplain.setLineWrap(true);
        txtplain.setRows(5);
        txtplain.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtplain);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("PLAIN TEXT");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("CIPHER TEXT");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("PLAIN TEXT");

        btnencryp.setBackground(new java.awt.Color(0, 0, 0));
        btnencryp.setForeground(new java.awt.Color(255, 255, 255));
        btnencryp.setText("ENCRYPTION");
        btnencryp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnencrypActionPerformed(evt);
            }
        });

        btndecryp.setBackground(new java.awt.Color(0, 0, 0));
        btndecryp.setForeground(new java.awt.Color(255, 255, 255));
        btndecryp.setText("DECRYPTION");
        btndecryp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndecrypActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("RANDOM KEY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("HƯỚNG DẪN SỬ DỤNG");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel7MouseReleased(evt);
            }
        });

        jMenu1.setText("File");

        menuFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuFile.setText("Mở menu");
        menuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileActionPerformed(evt);
            }
        });
        jMenu1.add(menuFile);

        menuFile1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuFile1.setText("Mở AES");
        menuFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFile1ActionPerformed(evt);
            }
        });
        jMenu1.add(menuFile1);

        menuFile2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menuFile2.setText("Mở RSA");
        menuFile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFile2ActionPerformed(evt);
            }
        });
        jMenu1.add(menuFile2);

        menuFile3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menuFile3.setText("Mở BowlsFish");
        menuFile3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFile3ActionPerformed(evt);
            }
        });
        jMenu1.add(menuFile3);

        menuFile4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_QUOTE, 0));
        menuFile4.setText("Tắt tất cả mã hóa");
        menuFile4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFile4ActionPerformed(evt);
            }
        });
        jMenu1.add(menuFile4);

        menuFile5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        menuFile5.setText("Tắt chương trình");
        menuFile5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFile5ActionPerformed(evt);
            }
        });
        jMenu1.add(menuFile5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtprivatekey, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                            .addComponent(txtkeypublic, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnencryp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel7)))
                                .addGap(143, 143, 143)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jScrollPane3)))))))
                .addGap(0, 23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndecryp)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(txtkeypublic, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 23, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtprivatekey, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnencryp)))
                .addGap(18, 18, 18)
                .addComponent(btndecryp)
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            try {
                // TODO add your handling code here:
                randomKey();
            } catch (InvalidKeySpecException ex) {
                Logger.getLogger(RSA.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(RSA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnencrypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnencrypActionPerformed
        
        try {
            if(txtkeypublic.getText().equals("")|| txtprivatekey.getText().equals(""))
            {
                JOptionPane.showMessageDialog(rootPane,"CHƯA TẠO KEY \n NHẤN RANDOM ĐỂ TẠO KEY");
                return;
            }
            if(txtinput.getText().equals(""))
            {
                JOptionPane.showMessageDialog(rootPane,"CHƯA NHẬP NỘI DUNG ĐỂ MÃ HÓA ");
                return;
            }
            // TODO add your handling code here:
            //tạo public key
            X509EncodedKeySpec spec = new X509EncodedKeySpec(Base64.getDecoder().decode(txtkeypublic.getText()));
            KeyFactory factory = KeyFactory.getInstance("RSA");
            try {
                PublicKey pubKey = factory.generatePublic(spec);
                Cipher c = Cipher.getInstance("RSA");
                c.init(Cipher.ENCRYPT_MODE, pubKey);
                String msg =txtinput.getText();
                byte encryptOut[] = c.doFinal(msg.getBytes());
                String strEncrypt = Base64.getEncoder().encodeToString(encryptOut);
                txtcipher.setText(strEncrypt);
            } catch ( NoSuchPaddingException | InvalidKeyException | IllegalBlockSizeException | BadPaddingException ex) {
              JOptionPane.showMessageDialog(rootPane,"VĂN BẢN MÃ HÓA KHÔNG HỢP LỆ \n ĐỘ DÀI QUÁ LỚN");
            }
            catch (InvalidKeySpecException ex )
            {
                JOptionPane.showMessageDialog(rootPane,"KEY KHÔNG HỢP LỆ");
            }
        } catch (NoSuchAlgorithmException ex) {
            JOptionPane.showMessageDialog(rootPane,"VĂN BẢN MÃ HÓA KHÔNG HỢP LỆ -- ");
        }
        catch (IllegalArgumentException ex){
            JOptionPane.showMessageDialog(rootPane,"KEY KHÔNG HỢP LỆ");
        }
        
    }//GEN-LAST:event_btnencrypActionPerformed

    private void btndecrypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndecrypActionPerformed
        try {
            // TODO add your handling code here:
            PKCS8EncodedKeySpec spec = new PKCS8EncodedKeySpec(Base64.getDecoder().decode(txtprivatekey.getText()));
            KeyFactory factory = KeyFactory.getInstance("RSA");
            PrivateKey priKey = factory.generatePrivate(spec);
            // giải mã
            Cipher c = Cipher.getInstance("RSA");
            c.init(Cipher.DECRYPT_MODE, priKey);
            byte decryptOut[] = c.doFinal(Base64.getDecoder().decode(txtcipher.getText()));
            txtplain.setText(new String(decryptOut));
        } catch (NoSuchAlgorithmException | InvalidKeySpecException | NoSuchPaddingException | InvalidKeyException | IllegalBlockSizeException | BadPaddingException ex) {
            JOptionPane.showMessageDialog(rootPane,"KEY KHÔNG HỢP LỆ");
        }
        catch(IllegalArgumentException  ex){
            JOptionPane.showMessageDialog(rootPane,"MẬT MÃ KHÔNG HỢP LỆ");
        }
    }//GEN-LAST:event_btndecrypActionPerformed

    private void jLabel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseReleased
        
        JOptionPane.showMessageDialog(rootPane,"NHẬP HOẶC NHẤN RANDOM KEY ĐỂ SINH KEY "
                + "\nNHẬP THÔNG TIN VÀO PLAINTTEXT \nNHẤN ENCRYPTION ĐỂ TIẾN HÀNH MÃ HÓA.\nNHẤN DECRYPTION ĐỂ TIẾN HÀNH GIẢI MÃ"
                ,"HƯỚNG DẪN SỬ DỤNG",JOptionPane.QUESTION_MESSAGE);
                
    }//GEN-LAST:event_jLabel7MouseReleased

    //Mở nhanh AES qua F2
    private void menuFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFile1ActionPerformed
        AES.testGuiAES().setVisible(true);
    }//GEN-LAST:event_menuFile1ActionPerformed

    private void menuFile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFile2ActionPerformed
        JOptionPane.showMessageDialog(null,"Form RSA đã hoạt động!"
                ,"Thông báo",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuFile2ActionPerformed

    //Tắt tất cả các mã hóa đang chạy qua phím `
    private void menuFile4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFile4ActionPerformed
       AES.testGuiAES().setVisible(false);
       RSA.testGuiRSA().setVisible(false);
       Blowfish.testBlowFish().setVisible(false);
    }//GEN-LAST:event_menuFile4ActionPerformed

    private void menuFile3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFile3ActionPerformed
         Blowfish.testBlowFish().setVisible(true);
    }//GEN-LAST:event_menuFile3ActionPerformed

    //Tắt chương trình nhanh qua phím ESC
    private void menuFile5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFile5ActionPerformed
        int n = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn thoát", "EXIT?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null);
        
        if(n == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_menuFile5ActionPerformed

    private void menuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileActionPerformed
        MainGUI.testMainGUI().setVisible(true);
    }//GEN-LAST:event_menuFileActionPerformed

    private void txtprivatekeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprivatekeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprivatekeyActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndecryp;
    private javax.swing.JButton btnencryp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem menuFile;
    private javax.swing.JMenuItem menuFile1;
    private javax.swing.JMenuItem menuFile2;
    private javax.swing.JMenuItem menuFile3;
    private javax.swing.JMenuItem menuFile4;
    private javax.swing.JMenuItem menuFile5;
    private javax.swing.JTextArea txtcipher;
    private javax.swing.JTextArea txtinput;
    private javax.swing.JTextField txtkeypublic;
    private javax.swing.JTextArea txtplain;
    private javax.swing.JTextField txtprivatekey;
    // End of variables declaration//GEN-END:variables
}
